apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: pbv4rfb7s-python
  janus-idp.io/tekton: pbv4rfb7s-python
  backstage.io/kubernetes-id: pbv4rfb7s-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pbv4rfb7s-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
